version: "3.8"
services:
  testing:
    build:
      context: .
    container_name: testing
    image: bats-testing:${TAG}
    volumes:
      - "$PWD:/src"
    command: ["/bin/bash"]
    entrypoint: ["/bin/bash", "/src/scripts/entrypoint.bash"]